development:
  clients:
    default:
      database: learn_sidekiq_development
      hosts:
        - localhost:27017
      options:

test:
  clients:
    default:
      database: learn_sidekiq_test
      hosts:
        - localhost:27017
      options:
        read:
          mode: :primary
        max_pool_size: 1
